### ISSUE TITLE
Unable to generate translations with latest po4a

### ISSUE THREAD

**Issue by elstoc** [darktable-org/dtdocs#563]
With latest version of po4a (v0.69) on ArchLinux, if I run `./generate-translations.sh --no-translations` from the tools directory, it fails with the following output:

```
/usr/bin/vendor_perl/po4a
Generating the POT and PO files.
Updating po/content.pot:Unknown format type: text.
po4a::chooser: Module loading error: Can't locate Syntax/Keyword/Try.pm in @INC (you may need to install the Syntax::Keyword::Try module) (@INC contains: /usr/lib/perl5/5.36/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.36/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.36/core_perl /usr/share/perl5/core_perl) at /usr/share/perl5/vendor_perl/Locale/Po4a/Text.pm line 61.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/Locale/Po4a/Text.pm line 61.
Compilation failed in require at (eval 36) line 1.
BEGIN failed--compilation aborted at (eval 36) line 1.

List of valid formats:
  - asciidoc: AsciiDoc format.
  - dia: uncompressed Dia diagrams.
  - docbook: DocBook XML.
  - guide: Gentoo Linux's XML documentation format.
  - ini: INI format.
  - kernelhelp: Help messages of each kernel compilation option.
  - latex: LaTeX format.
  - man: Good old manual page format.
  - pod: Perl Online Documentation format.
  - rubydoc: Ruby Documentation (RD) format.
  - sgml: either DebianDoc or DocBook DTD.
  - texinfo: The info page format.
  - tex: generic TeX documents (see also latex).
  - text: simple text document.
  - wml: WML documents.
  - xhtml: XHTML documents.
  - xml: generic XML documents (see also docbook).
  - yaml: YAML documents.
```

Works fine on v0.63

**Comment by elstoc** [comment]
Looks like it was a missing perl module on ArchLinux (`perl-syntax-keyword-try`)
